sudo: false
language: ruby
dist: bionic

rvm:
  - 2.3.3
  - 2.5
  - 2.6
  - 2.7
before_install:
    - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
    - gem install bundler -v '< 2'